### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'contains')

### ISSUE THREAD

**Issue by guyschlider** [fregante/webext-polyfill-kinda#3]
Hey,

I'm using `content-scripts-register-polyfill` which depends on this lib,

Since I'm trying to migrate to manifest v3 I'm getting a new error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'contains')`
For this line:

```
async function isOriginPermitted(url) {
    return chromeP.permissions.contains({
        origins: [new URL(url).origin + '/*']
    });
}
```

**Comment by guyschlider** [comment]
Ok, just saw content-scripts-register-polyfill has a new version that supports manifest v3

my bad, sorry

**Comment by fregante** [comment]
Hi, this should work regardless of the manifest version because the Permission API hasn't changed. I'm not sure why it would throw an error here though 🤭

**Comment by fregante** [comment]
By the way you might want to use the new native API instead: chrome.scripting.registerContentScript (or something like that)

I think eventually I'll change the polyfill to use that where possible, but if you're building just for chrome you can use it directly.
